### PR TITLE
Issue 1555: Class link is flaky

### PR DESCRIPTION
**Pull request by MegaGeese**
log out user before class login

### CODE REVIEW

**Comment by JRustyHaner** [comment]
@imrryr August and  I agree, this is probably a temporary solution. We should have an interface for students to select their class after  login has occurred.

**Comment by imrryr** [comment]
Not sure I understand. Are you saying that coding it so that each class has a link is not feasible? Why can't the login simply pass the information about what class to select? Have we tried that?

**Comment by imrryr** [comment]
Your solution presents a very different specification than I am trying to achieve. I think it provides  a lot of simplicity for students to have a direct link. Also, your talking about doing a lot more coding than I am, since we would still need to build this new login with teacher selection (which would need to be separate from regular login to prevent outsiders from logging in as students). Having a direct link makes it more private. My fix is very simple in the way I think about it. Makes it easier, but perhaps I am not understanding the complexity of some part of this issue of providing a link that has the class selection passed in it.

**Comment by JRustyHaner** [comment]
@imrryr I understand that. That was not my gist. Forcing students to logout and back in is adding an extra step for logged in users. A selection interface located in the lesson select screen for logged in users in who have used a class link previously is ideal.  We didn't say that the link is not feasible, it's just an annoyance for the users who stay logged in and return to force them to log out before selecting a lesson.

**Pull request merged**
