### PR TITLE
Iss1381: removed skip from data input field

### PR DESCRIPTION
**Pull request by JRustyHaner**
How to test: 

-Make sure feedback latency is reading correct when skip button is used.
-Make sure input is the selected answer, not [skip] or continueStudy

### CODE REVIEW

**Comment by imrryr** [comment]
Please explain what this is doing.... seems weird  if it is not a skip, we just do the same thing??? But I don't even know what this fixes at the same time. Doesn't seem like it addresses the latency issue...


console.log('showUserFeedback');
  userFeedbackStart = Date.now();
  console.log('showUserFeedback')
  if(!isSkip){
    userFeedbackStart = Date.now();
  }

**Comment by JRustyHaner** [comment]
@imrryr it's because of how the skip button was initially coded. It'll take a lot of time to fix right (a refactor on how it works)

So, when the skip button was introduced (a while ago, years), it basically did the same thing as clicking an answer. The script still continued through the answer assessment and feedback. It still does that, so effectively we are answering the card twice if we click skip during feedback. To not refactor it immediately, we have to get the calculations from the first time to get the timestamp of when the feedback started.

**Comment by imrryr** [comment]
@JRustyHaner ok, this is bad design, and probably took about 4 times longer to originally code than needed. The skip study button is simply a relabeled continue button. It would never need to be treated like this. Not blaming you surely.

**Review by imrryr — APPROVED** [review]

**Comment by JRustyHaner** [comment]
@imrryr It is a bit of a mess, but we'll get to it. I'm glad you asked though, since this is surely not how you intended the original skip button to work, yet it ended up that way.

**Pull request merged**
