### PR TITLE
Iss1394: add emails to teachers and all admins on deploy

### LINKED ISSUE #1394: Email Notification for staging releases
If people are registered as teachers or admins, they should get an automatic email for each staging release for this change. I'm not sure Shelbi got the email that her code is up (at least, I think it must be because the issues are down.)

### PR DESCRIPTION
**Pull request by JRustyHaner**
Fixes #1394 

This modification sends an email to each user mentioned as teachers, admins, or owner in initroles in settings.json. It will not send duplicates emails if the email is listed multiple times.

Bonus:

The readout for disk usage will be more accurate and in gigabytes. Showing block sizes is a bit unfriendly.

### CODE REVIEW

**Review by imrryr — APPROVED** [review]
@MegaGeese I'll need your review on this, since it is database stuff

**Comment by JRustyHaner** [comment]
@imrryr  there isn't any database manipulation here. The code reads data from the settings.json file and sends an email to all emails that are in the initroles array.

**Comment by imrryr** [comment]
@JRustyHaner Are you just saying that the teacher and admin settings are in the json file, not the database? I would still defer to @MegaGeese and not try to approve this

**Comment by JRustyHaner** [comment]
@JRustyHaner yes, but I concur. It's best to review code.

**Pull request merged**
